initial commit
tommyannypeter/py-Tower-of-Somewhat pull request #1
Opened 2022-06-10 16:19 UTC by darren016

Initialize Balls and Board class

2022-06-10 16:20 UTC, tommyannypeter commented
每個class各自一個檔案吧

2022-06-11 04:06 UTC, peteranny reviewed
有個README和初始的執行指令會比較好，讓開發者有跡可循

2022-06-11 06:02 UTC, peteranny commented on Board.py
> +        return ""
這應該是回傳字串且沒有副作用（print)的方法才對

2022-06-11 06:02 UTC, peteranny commented on basics.py
> +class Ball:
這個檔案的Ball 和Board和另一個有什麼差別呢

2022-06-11 06:02 UTC, peteranny commented on test.py
> +    print(board)
可以在這裡做assert（驗證球是不是真的有6*5之類）

2022-06-12 14:28 UTC, peteranny reviewed
看起來差不多了
最後建議加個Makefile
```
test:
    python test.py
```
然後一個README
```md
To run the test, run `make test`.
```
這樣自己測試也比較方便，以後review也會比較知道進入點在哪裡

2022-06-13 05:49 UTC, peteranny approved these changes

2022-06-13 06:13 UTC, tommyannypeter approved these changes

2022-06-13 06:13 UTC, tommyannypeter commented on Ball.py
> +        return Color(random.randint(1, 5))
我看到這個解法
https://stackoverflow.com/questions/47353555/how-to-get-random-value-of-attribute-of-enum-on-each-iteration

2022-06-13 06:46 UTC, peteranny requested changes

2022-06-13 06:46 UTC, peteranny commented on Ball.py
> +        return random.choice([Color.RED, Color.GREEN, Color.BLUE, Color.YELLOW, Color.PURPLE])
這裡怪怪的，通常會是 `def setColor(self, color)`
如果這裡只是初始值隨意的話，應該是
```suggestion
    def __init__(self):
        self.color = random.choice([Color.RED, Color.GREEN, Color.BLUE, Color.YELLOW, Color.PURPLE])
```

2022-06-13 07:19 UTC, tommyannypeter commented on Ball.py
> +        return random.choice([Color.RED, Color.GREEN, Color.BLUE, Color.YELLOW, Color.PURPLE])
順帶一提，把naming統一一下，method name要camelCase還是要snake_case呢？
我看了一下這個PR兩個都有用到

2022-06-13 07:37 UTC, peteranny approved these changes

2022-06-13 15:58 UTC, merged